### PR TITLE
UI / UX fixes

### LINKED ISSUE #144: Login screen can be rotated
Login screen when rotated breaks, doesn't crash but just looks dumb. Should be a easy fix.

### LINKED ISSUE #145: Change post to Facebook dialog to reflect lending or offering

### PR DESCRIPTION
**Pull request by connerleverett**
Fixes: 
1)login screen rotation 
2)post to FB dialog to reflect lend or borrow
3) Added more analytics
This closes  #145 closes #144

### CODE REVIEW

File: Bumerang/app/src/main/java/com/seng480b/bumerang/fragments/CreateRequestFragment.java [hunk 1]
```diff
@@ -75,6 +76,7 @@
     private ImageView chosenImage;
 
     CheckBox postToFacebook;
+    RadioButton borrow;
```
Comment (bjschnell) [inline Bumerang/app/src/main/java/com/seng480b/bumerang/fragments/CreateRequestFragment.java]: We've already set up the radio button to automatically reflect the selected type in the requestType variable. I think you should change it to use the request type rather than the input from the radio button. Just my thoughts.

File: Bumerang/app/src/main/java/com/seng480b/bumerang/fragments/BrowseFragment.java [hunk 2]
```diff
@@ -2,6 +2,7 @@
 
 import android.app.Activity;
 import android.content.Context;
+import android.graphics.Color;
```
Comment (bjschnell) [inline Bumerang/app/src/main/java/com/seng480b/bumerang/fragments/BrowseFragment.java]: If you make the other edits remove this import as well, as it's not necessary.

File: Bumerang/app/src/main/java/com/seng480b/bumerang/fragments/CreateRequestFragment.java [hunk 3]
```diff
@@ -365,16 +379,29 @@ private Request createRequest() {
         }
     }
 
-    private void postToFacebook(String titleStr, String descriptionStr, int hoursInt, int minutesInt) {
+    private void postToFacebook(boolean borrow,String titleStr, String descriptionStr, int hoursInt, int minutesInt) {
```
Comment (bjschnell) [inline Bumerang/app/src/main/java/com/seng480b/bumerang/fragments/CreateRequestFragment.java]: Same thing as above, make this RequestType instead of a boolean.

File: Bumerang/app/src/main/java/com/seng480b/bumerang/fragments/CreateRequestFragment.java [hunk 4]
```diff
@@ -365,16 +379,29 @@ private Request createRequest() {
...
 
-        String quote = "Hey everybody, I'm currently looking for a " + titleStr + ".";
-        if (descriptionStr.equals("")) {
-            quote = quote + " I need it within " + String.valueOf(hoursInt + ((double) minutesInt / 60)) + " hours please!";
-        } else {
-            quote = quote + " I would describe it as a " + descriptionStr + ". I need it within " +
-                    String.valueOf(hoursInt + ((double) minutesInt / 60)) + " hours please!";
+        String quote = "";
+
+        if (borrow==true) {
```
Comment (bjschnell) [inline Bumerang/app/src/main/java/com/seng480b/bumerang/fragments/CreateRequestFragment.java]: then just check if requestType is = borrow, or lend. We have constants for them somewhere haha.
